#!/bin/bash

# Set csv delimiter to ;
IFS=';'
# Set nocasematch, so the if string comparision is case insensitive
shopt -s nocasematch

ARRAY=()
echo "" > types.txt

# for all years until 2020 extract all glider types
for year in {2000..2020}; do

	# read existing types from older loops
	if [ -f types.txt ]; then
		ARRAY=($(cat types.txt))
	fi

	# check if year csv exists
	if [ -f csv/${year}.csv ]; then

		# read the csv line per line
		while read rank change wkz name type points; do

			# add to types array if not in there yet
			if [[ ! "${ARRAY[@]}" =~ "${type}" ]]; then
				ARRAY+=(${type})
			fi

		done < csv/${year}.csv

		# save the types into the file types.txt
		echo "${ARRAY[*]}" > types.txt

	fi
	
done

# set all types on top of data file with a column of the year in the beginning
echo "year;${ARRAY[*]}" > data.txt

# for all years until 2020 count the glider types
for year in {2000..2020}; do

	# check if year csv exists
	if [ -f csv/${year}.csv ]; then

		COUNT=""
		NRTOT="$(cat csv/${year}.csv | wc -l | awk '{print $1}')"

		# for each glider type
		for i in "${ARRAY[@]}"; do

			# add semicolon as delimiter if not first loop
			if [[ "${COUNT}" != "" ]]; then
				COUNT+=";"
			fi

			# add counted glider types to the variable
			NRGLD="$(grep -oi ${i} csv/${year}.csv | wc -l | awk '{print $1}')"
			COUNT+="$(echo \"$(( 200*${NRGLD}/${NRTOT} - 100*${NRGLD}/${NRTOT} ))\" | bc )"

		done

		# save year and counted gliders to textfile
		echo "${year};${COUNT}" >> data.txt

	fi

done

# returning content of data.txt
cat data.txt
